### PR TITLE
brainstorming some OO refactoring

### PR DESCRIPTION
**Pull request by jrob8577**

### CODE REVIEW

**Comment by tmytrn** [comment]
It didn't work

**Comment by jrob8577** [comment]
What didn't work?

**Comment by tmytrn** [comment]
I tried registering a new account last week, and it threw a bunch of errors that I don't remember. Just tried again and it works omg sorry for doubting you!

**Comment by jrob8577** [comment]
Trust, but verify :). I wasn't saying I thought it was perfect, was just curious if there was something that could be fixed.

**Pull request closed without merging**
